### ISSUE TITLE
docker部署显示yml is invalid

### ISSUE THREAD

**Issue by dapeng1115** [NiuStar/arkoselabs_token_api#1]
求助大佬，docker部署报错
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.arkoselabs_token_api.get.environment contains an invalid type, it should be an object, 
试过把environment的变量改成 =， 还是有问题

**Comment by NiuStar** [comment]
version: '3'
services:
  arkoselabs_token_api.get:
    container_name: arkoselabs_token_api.get
    image: 24802117/arkoselabs_token_api.get:latest
    environment:
      db: false
      http_proxy: http://localhost:40000
    volumes:
      - ./chat.openai.com.har:/home/app/chat.openai.com.har
    ports:
      - 8080:8081
    restart: unless-stopped
   
   
  你先尝试一下这个，不使用db，如果还有问题，请贴出来你的yaml，好进行检查

**Comment by dapeng1115** [comment]
感谢大佬！这个我删了volumes或者建一个空的chat.openai.com.har，服务可以起来，但使用gpt 4token的时候还是time out，所以chat.openai.com.har 这个文件应该怎么正确生成？

**Comment by NiuStar** [comment]
har具体教程你可以百度谷歌哈，大概就是你用谷歌浏览器打开chat.openai.com，打开开发者控制台，然后正常的请求一次gpt4的会话，它会有请求token的请求，你在控制台网络那里选择任意一个网络请求，右键，选择以HAR保存就可以了
