### ISSUE TITLE
请问需要哪个的 HAR 文件？

### ISSUE THREAD

**Issue by MuelNova** [NiuStar/arkoselabs_token_api#2]
![image](https://github.com/NiuStar/arkoselabs_token_api/assets/68760718/87b69a0b-43fc-4462-9879-9af2f2074291)
抓取了 `/conversation/` 的 HAR 文件提示如下

**Comment by NiuStar** [comment]
har中需要包含https://tcr9i.chat.openai.com/fc/gt2/的请求，如果没有解析到这个接口，就会导致后面报这个错误，如果方便，你可以在你的har中找一下有没有这个请求
