### ISSUE TITLE
没有对应的har

### ISSUE THREAD

**Issue by yvenxx** [NiuStar/arkoselabs_token_api#5]
compose.yaml

services:
  arkoselabs_token_api.get:
    container_name: arkoselabs_token_api.get
    image: 24802117/arkoselabs_token_api.get:latest
    ports:
      - 8080:8081
    volumes:
      - type: bind
        source: ./chat.openai.com.har
        target: /home/app/chat.openai.com.har
    restart: unless-stopped

每次请求/token时，都会显示如下
![image](https://github.com/NiuStar/arkoselabs_token_api/assets/44969127/a50b9b3d-0124-4c0f-b7c0-2c8b04ef021a)

har文件是从登录开始就取的，开了历史记录。还是无法请求到。
这里是请求到tcr9i的那个地址
![image](https://github.com/NiuStar/arkoselabs_token_api/assets/44969127/edce6005-0cec-46b5-93ba-a474970f0000)

我刚开始以为我没请求到那个地址，所以关了issue，发现请求到了还是有问题，所以又开了

希望大佬解答

**Comment by jeffersonchou** [comment]
我也遇到这个问题，GPT-4一直不行，求解...

**Comment by d1h1r1** [comment]
我也是一直这种情况 funcaptcha_error	"没有对应的har"

**Comment by NiuStar** [comment]
har中需包含https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147请求
