### ISSUE TITLE
登录404

### ISSUE THREAD

**Issue by superen7527** [NiuStar/arkoselabs_token_api#6]
你好，我想用这个项目，实现自动登录获取Accesstoken

不过我不知道还有哪里有教程，跟着这个项目里两个月前的compose文件，和issue里几个compose示例代码试着搭建了一下，然后放了har映射目录。
结果几个token login_token都提示har不行，但是我需要的是9号更新的提交 { "email":"XXX", "password":"XXX" } 登录获取token。但是访问页面一直404，用 http://gpttoken.mukj.cn/api/login 也不行。也是404 请问一下：

这个项目支持获取Accesstoken吗？

我在云服务器上跑有问题吗还是必须本地跑？

har里有 tcr9i的请求，但是用不了，还有什么需要注意的吗？

另外有没有别的地方有该项目的教程？我是偶然别的地方看到过来的，不知道大家是怎么用的，有没有别的讨论地方？

**Comment by NiuStar** [comment]
登录需要有另外一个har和会话的har不是同一个哈
