### ISSUE TITLE
由于3.5现在也开启了arkose，我用3.5的账号抓包，启动了会显示没有对应的har

### ISSUE THREAD

**Issue by xiaosaaaa** [NiuStar/arkoselabs_token_api#7]
但是我抓到的包名是https://tcr9i.chat.openai.com/fc/gt2/public_key/3D86FBBA-9D22-402A-B512-3420086BA6CC
而不是https://tcr9i.chat.openai.com/fc/gt2/public_key/35536E1E-65B4-4D96-9D97-6ADB7EFF8147
是不是这个原因才导致运行后出现没有对应的har，有什么解决办法么？

**Comment by NiuStar** [comment]
如果你需要的token的public_key 不同，请使用http://localhost:8080/other_token?pk=3D86FBBA-9D22-402A-B512-3420086BA6CC
这个接口，

**Comment by xiaosaaaa** [comment]
十分感谢，我去试试。
